# Generated by Django 4.2.2 on 2023-06-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment_users'},
        ),
        migrations.RemoveIndex(
            model_name='postcomment',
            name='blog_postco_created_fc0f25_idx',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['created'], name='blog_postco_created_0241eb_idx'),
        ),
    ]
